using System;
using System.Runtime.InteropServices;

namespace Septerra.Core.Hooks
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public unsafe struct SC_CombatListEntry
    {
        public ActorInfo2* Actor;
        public CHHeader* CHHeader;
        public Int16* ptr_field_8;
        public SC_CombatListEntry* linkedEntries;
        public SC_CombatListEntry* linkedEntries2;
        public SC_CombatListEntry* BattleTarget;
        public int field_18;
        public Int32 field_1C;
        public Int16 field_20;
        public Int16 field_22;
        public Int16 field_24;
        public Int16 field_26;
        public Int16 field_28;
        public Int16 gap_2A;
        public Int32 field_2C;
        public Int32 field_30;
        public Int32 field_34;
        public Int32 field_38;
        public Int32 field_3C;
        public Int32 gap_40_1;
        public Int32 gap_40_2;
        public float field_48_Coeff;
        public SC_CombatListEntry_Quad field_4C_1;
        public SC_CombatListEntry_Quad field_4C_2;
        public SC_CombatListEntry_Quad field_4C_3;
        public SC_CombatListEntry_Quad field_4C_4;
        public SC_CombatListEntry_Quad field_4C_5;
        public SC_CombatListEntry_Quad field_4C_6;
        public SC_CombatListEntry_Quad field_4C_7;
        public SC_CombatListEntry_Quad field_4C_8;
        public SC_CombatListEntry_Quad field_4C_9;
        public SC_CombatListEntry_Quad field_4C_10;
        public SC_CombatListEntry_Quad field_4C_11;
        public SC_CombatListEntry_Quad field_4C_12;
        public SC_CombatListEntry_Quad field_4C_13;
        public SC_CombatListEntry_Quad field_4C_14;
        public SC_CombatListEntry_Quad field_4C_15;
        public float field_C4;
        public float field_C8;
        public Int32 field_CC;
        public Int32 gap_D0;
        public CHSegment2* field_D4;
        public CHSegment3* field_D8;
        public fixed Byte gap_DC[20];
        public Int32 field_F0;
        public fixed Byte gap_F4[300];
        public Int32 field_220;
        public fixed Byte gap_224[4];
        public fixed Byte gap228[2280];
        public Int32 switchableType;
        public Int16 field_B14;
        public fixed Byte gap_B16[6];
        public Int32 field_B1C;
        public Int32 gap_B20;
        public byte field_B24;
        public byte field_B25;
        public Int16 field_B26;
        public Int32 field_B28;
        public Int32 someBool1;
        public Int32 field_B30;
        public Int32 field_B34;
        public Int32 field_B38;
        public fixed Byte gap_B3C[20];
        public float field_B50;
        public Int32 gap_B54;
        public Int32 field_B58;
        public Int32 field_B5C;
        public Int32 field_B60;
        public Int32 field_B64;
        public float field_B68;
        public float SomeAngle;
        public float field_B70;
        public float SomeDistance;
        public Int32 field_B78;
        public Int32 field_B7C;
        public Int32 field_B80;
        public fixed Byte gap_B84[36];
        public Int32 field_BA8;
        public Int32 field_BAC;
        public Int32 gap_BB0_1;
        public Int32 gap_BB0_2;
        public byte field_BB8;
        public byte field_BB9;
        public byte field_BBA;
        public byte field_BBB;
        public Int32 gap_BBC;
        public Int32 field_BC0;
        public Int32 field_BC4;
        public int field_BC8;
        public Int32 someBool2;
        public Int32 someBool3;
        public fixed Byte gap_BD4[12];
        public Int16 field_BE0;
        public Int16 field_BE2;
        public UInt16 field_BE4;
    };
}